part of concept_attribute;

String citiesInJson() {
  var json = '''
[
{ "city" : "Toronto" },
{ "city" : "Québec" },
{ "city" : "Montréal" },
{ "city" : "Tehran" },
{ "city" : "Manila" },
{ "city" : "Shenzhen" },
{ "city" : "Mexico City" },
{ "city" : "Osaka" },
{ "city" : "New York City" },
{ "city" : "Kinshasa" },
{ "city" : "Istanbul" },
{ "city" : "Los Angeles" },
{ "city" : "London" },
{ "city" : "Kankan" },
{ "city" : "Dhaka" },
{ "city" : "Conakry" },
{ "city" : "Los Angeles" },
{ "city" : "Shenzhen" },
{ "city" : "Sao Paulo" },
{ "city" : "Tokyo" },
{ "city" : "Mexico City" },
{ "city" : "Beijing" },
{ "city" : "Rio de Janeiro" },
{ "city" : "Beijing" },
{ "city" : "Osaka" },
{ "city" : "Guangzhou" },
{ "city" : "Boké" },
{ "city" : "Dhaka" },
{ "city" : "Lima" },
{ "city" : "Guangzhou" },
{ "city" : "Dhaka" },
{ "city" : "Mexico City" },
{ "city" : "Manila" },
{ "city" : "Tianjin" },
{ "city" : "Kinshasa" },
{ "city" : "Guangzhou" },
{ "city" : "Buenos Aires" },
{ "city" : "Beijing" },
{ "city" : "Delhi" },
{ "city" : "Istanbul" },
{ "city" : "Shanghai" },
{ "city" : "Buenos Aires" },
{ "city" : "Manila" },
{ "city" : "Windsor" },
{ "city" : "Mumbai" },
{ "city" : "Lima" },
{ "city" : "Tehran" },
{ "city" : "Bogota" },
{ "city" : "New Wark" },
{ "city" : "Abidjan" },
{ "city" : "Istanbul" },
{ "city" : "Kolkata" },
{ "city" : "Kyoto" }
]
  ''';
  return json;
}

