
// http://www.json.org/
// http://jsonformatter.curiousconcept.com/

// rename dartling to yourDomainName
// rename Skeleton to YourModelName

// lib/dartling/skeleton/json/data.dart

var conceptAttributeDataJson = @'''
{
   "entries":[
      {
         "concept":"City",
         "entities":[
            {
               "oid":"1350580563263",
               "name":"Toronto",
               "code":null
            },
            {
               "oid":"1350580563267",
               "name":"Québec",
               "code":null
            },
            {
               "oid":"1350580563268",
               "name":"Montréal",
               "code":null
            }
         ]
      },
      {
         "concept":"FirstName",
         "entities":[
            {
               "oid":"1350580563278",
               "firstName":"David",
               "code":null
            },
            {
               "oid":"1350580563279",
               "firstName":"Dzenan",
               "code":null
            },
            {
               "oid":"1350580563281",
               "firstName":"Rafik",
               "code":null
            },
            {
               "oid":"1350580563282",
               "firstName":"Timur",
               "code":null
            }
         ]
      },
      {
         "concept":"LastName",
         "entities":[
            {
               "lastName":"Curtis",
               "oid":"1350580563271",
               "code":null
            },
            {
               "lastName":"Benmoussa",
               "oid":"1350580563272",
               "code":null
            },
            {
               "lastName":"Ridjanovic",
               "oid":"1350580563274",
               "code":null
            },
            {
               "lastName":"Kaba",
               "oid":"1350580563275",
               "code":null
            }
         ]
      },
      {
         "concept":"Email",
         "entities":[
            {
               "emailaddress":"david.curtis@hotmail.ca",
               "oid":"1350580563284",
               "code":null
            },
            {
               "emailaddress":"rafik.benmoussa@hotmail.ca",
               "oid":"1350580563286",
               "code":null
            },
            {
               "emailaddress":"timur.ridjanovic@gmail.ca",
               "oid":"1350580563287",
               "code":null
            },
            {
               "emailaddress":"dzenan.ridjanovic@gmail.ca",
               "oid":"1350580563289",
               "code":null
            }
         ]
      }
   ],
   "domain":"Concept",
   "model":"Attribute"
}
''';