part of concept_attribute;

// http://www.json.org/
// http://jsonformatter.curiousconcept.com/

// rename dartling to yourDomainName
// rename Skeleton to YourModelName

// lib/dartling/skeleton/json/data.dart

var conceptAttributeDataJson = r'''
{
   "entries":[
      {
         "concept":"City",
         "entities":[
            {
               "oid":"1351367861734",
               "name":"Toronto",
               "code":null
            },
            {
               "oid":"1351367861738",
               "name":"Québec",
               "code":null
            },
            {
               "oid":"1351367861739",
               "name":"Montréal",
               "code":null
            }
         ]
      },
      {
         "concept":"FirstName",
         "entities":[
            {
               "oid":"1351367861748",
               "firstName":"David",
               "code":null
            },
            {
               "oid":"1351367861749",
               "firstName":"Dzenan",
               "code":null
            },
            {
               "oid":"1351367861751",
               "firstName":"Rafik",
               "code":null
            },
            {
               "oid":"1351367861752",
               "firstName":"Timur",
               "code":null
            }
         ]
      },
      {
         "concept":"LastName",
         "entities":[
            {
               "lastName":"Curtis",
               "oid":"1351367861741",
               "code":null
            },
            {
               "lastName":"Benmoussa",
               "oid":"1351367861743",
               "code":null
            },
            {
               "lastName":"Ridjanovic",
               "oid":"1351367861744",
               "code":null
            },
            {
               "lastName":"Kaba",
               "oid":"1351367861746",
               "code":null
            }
         ]
      },
      {
         "concept":"Email",
         "entities":[
            {
               "email":"david.curtis@hotmail.ca",
               "oid":"1351367861754",
               "code":null
            },
            {
               "email":"rafik.benmoussa@hotmail.ca",
               "oid":"1351367861756",
               "code":null
            },
            {
               "email":"timur.ridjanovic@gmail.ca",
               "oid":"1351367861757",
               "code":null
            },
            {
               "email":"dzenan.ridjanovic@gmail.ca",
               "oid":"1351367861758",
               "code":null
            }
         ]
      },
      {
         "concept":"About",
         "entities":[
            {
               "oid":"1351367861760",
               "about":"Student at UQTR , I love Basket ball! ",
               "code":null
            }
         ]
      },
      {
         "concept":"Category",
         "entities":[
            {
               "oid":"1351367861762",
               "category":"Politic",
               "code":null
            },
            {
               "oid":"1351367861764",
               "category":"Economy",
               "code":null
            },
            {
               "oid":"1351367861765",
               "category":"History",
               "code":null
            }
         ]
      },
      {
         "concept":"Description",
         "entities":[

         ]
      }
   ],
   "domain":"Concept",
   "model":"Attribute"
}
''';