name: concept_attribute
version: 0.1.0
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: A model with one attribute concepts for test data generation. dartling is a domain model framework for web applications.
homepage: http://ondart.me/
dependencies:
  browser: any
  dartling: any
  dartling_default_app: any
