name: concept_attribute
version: 0.0.8
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: A model with one attribute concepts for test data generation. Dartling is a domain model framework for web application prototypes. A new dartling project is copied and adapted from dartling_skeleton.
homepage: http://ondart.me/
dependencies:
  dartling:
    git: git://github.com/dzenanr/dartling.git
