name: concept_attribute
version: 0.1.1
description: A model with one attribute concepts for test data generation. dartling is a domain model framework for web applications.
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
documentation: 
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dartling:
    git: 'https://github.com/dzenanr/dartling.git'
  dartling_default_app:
    git: 'https://github.com/dzenanr/dartling_default_app.git'
